import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:share_plus/share_plus.dart';

import '../../data/models/visit.dart';
import '../../data/models/visit_form.dart';

/// Builds and shares a visit report PDF.
class VisitReportPdf {
  VisitReportPdf._();

  static Future<void> download({
    required Visit visit,
    VisitFormTemplate? template,
  }) async {
    final doc = pw.Document();
    final dateFmt = DateFormat('dd MMM yyyy · hh:mm a');
    final duration = _durationLabel(visit);

    final answerRows = <pw.Widget>[];
    if (visit.formAnswers.isNotEmpty) {
      for (final answer in visit.formAnswers) {
        answerRows.add(
          pw.Padding(
            padding: const pw.EdgeInsets.only(bottom: 8),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  answer.questionLabel,
                  style: pw.TextStyle(
                    fontWeight: pw.FontWeight.bold,
                    fontSize: 11,
                  ),
                ),
                pw.SizedBox(height: 2),
                pw.Text(
                  answer.displayValue().isEmpty ? '—' : answer.displayValue(),
                  style: const pw.TextStyle(fontSize: 11),
                ),
              ],
            ),
          ),
        );
      }
    } else if (visit.mcqAnswers.isNotEmpty) {
      visit.mcqAnswers.forEach((key, value) {
        answerRows.add(
          pw.Padding(
            padding: const pw.EdgeInsets.only(bottom: 6),
            child: pw.Text(
              '$key: $value',
              style: const pw.TextStyle(fontSize: 11),
            ),
          ),
        );
      });
    }

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (context) => [
          pw.Text(
            'Shine Gold — Visit Report',
            style: pw.TextStyle(
              fontSize: 20,
              fontWeight: pw.FontWeight.bold,
              color: PdfColor.fromInt(0xFFB8860B),
            ),
          ),
          pw.SizedBox(height: 6),
          pw.Text(
            visit.farmName,
            style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 16),
          _kv('Status', visit.status.name),
          _kv('Executive', visit.executiveName),
          _kv('Checked in', dateFmt.format(visit.startedAt.toLocal())),
          if (visit.endedAt != null)
            _kv('Checked out', dateFmt.format(visit.endedAt!.toLocal())),
          _kv('Duration', duration),
          if (visit.photoCount > 0 || visit.photos.isNotEmpty)
            _kv(
              'Photos',
              '${visit.photos.isNotEmpty ? visit.photos.length : visit.photoCount}',
            ),
          if (visit.hasVoiceNote ||
              (visit.voiceNotePath != null &&
                  visit.voiceNotePath!.trim().isNotEmpty))
            _kv('Voice note', 'Recorded'),
          pw.SizedBox(height: 18),
          pw.Text(
            'Field Report',
            style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 8),
          if (visit.textNote != null && visit.textNote!.trim().isNotEmpty)
            pw.Text(visit.textNote!.trim())
          else
            pw.Text('No written notes.'),
          if (answerRows.isNotEmpty) ...[
            pw.SizedBox(height: 18),
            pw.Text(
              'Form Answers',
              style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
            ),
            pw.SizedBox(height: 8),
            ...answerRows,
          ],
          if (template != null) ...[
            pw.SizedBox(height: 12),
            pw.Text(
              'Form: ${template.name}',
              style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700),
            ),
          ],
          pw.SizedBox(height: 24),
          pw.Text(
            'Generated by Shine Gold · ${DateFormat('dd MMM yyyy HH:mm').format(DateTime.now())}',
            style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
          ),
        ],
      ),
    );

    final bytes = await doc.save();
    final fileName =
        'visit_report_${visit.farmName.replaceAll(RegExp(r"[^a-zA-Z0-9]+"), "_")}_${visit.id.substring(0, visit.id.length.clamp(0, 8))}.pdf';

    if (kIsWeb) {
      await Printing.sharePdf(bytes: bytes, filename: fileName);
      return;
    }

    final dir = await getTemporaryDirectory();
    final file = File('${dir.path}/$fileName');
    await file.writeAsBytes(bytes, flush: true);

    try {
      await Share.shareXFiles(
        [XFile(file.path)],
        subject: 'Visit report — ${visit.farmName}',
        text: 'Shine Gold visit report for ${visit.farmName}',
      );
    } catch (_) {
      await Printing.layoutPdf(onLayout: (_) async => bytes);
    }
  }

  static pw.Widget _kv(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 4),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.SizedBox(
            width: 100,
            child: pw.Text(
              label,
              style: pw.TextStyle(
                fontWeight: pw.FontWeight.bold,
                fontSize: 11,
              ),
            ),
          ),
          pw.Expanded(
            child: pw.Text(value, style: const pw.TextStyle(fontSize: 11)),
          ),
        ],
      ),
    );
  }

  static String _durationLabel(Visit visit) {
    final mins = visit.durationMinutes;
    if (mins == null || mins <= 0) {
      if (visit.endedAt != null) {
        final seconds = visit.endedAt!.difference(visit.startedAt).inSeconds;
        final m = (seconds / 60).round();
        if (m < 60) return '$m min';
        return '${m ~/ 60}h ${m % 60}m';
      }
      return '—';
    }
    if (mins < 60) return '$mins min';
    return '${mins ~/ 60}h ${mins % 60}m';
  }
}
